version: '2'

services:
  db:
    container_name: petclinic-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: petclinic
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./scripts/mysql-init:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    container_name: petclinic-backend
    build:
      context: ./backend/
    command: /var/www/petclinic/backend/node_modules/.bin/nodemon src/index.js
    volumes:
      - ./backend/:/var/www/petclinic/backend
      - /var/www/petclinic/backend/node_modules
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  frontend:
    container_name: petclinic-frontend
    build:
      context: ./frontend/
    command: npm start
    volumes:
      - ./frontend/:/var/www/petclinic/frontend
      - /var/www/petclinic/frontend/node_modules
    depends_on:
      - backend
    ports:
      - "3001:3000"
